### ISSUE TITLE
更新似乎无效

### ISSUE THREAD

**Issue by MangoFish163** [ArcSurge/Termius-Pro-zh_CN#1]
更新似乎无效
`PS C:\Users\25592\AppData\Local\Programs\Termius> & D:/env/python312/python.exe c:/Users/25592/AppData/Local/Programs/Termius/lang.py
2024-10-23 17:17:40,384 - INFO - Running command: asar extract C:\Users\25592\AppData\Local\Programs\Termius\resources/app.asar C:\Users\25592\AppData\Local\Programs\Termius\resources/app
'asar' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-10-23 17:17:40,408 - INFO - Running command: asar pack C:\Users\25592\AppData\Local\Programs\Termius\resources/app C:\Users\25592\AppData\Local\Programs\Termius\resources/app.asar --unpack-dir {"node_modules/@termius,out"}
'asar' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-10-23 17:17:40,427 - ERROR - Command failed with error: Command 'asar pack C:\Users\25592\AppData\Local\Programs\Termius\resources/app C:\Users\25592\AppData\Local\Programs\Termius\resources/app.asar --unpack-dir {"node_modules/@termius,out"}' returned non-zero exit status 1.
2024-10-23 17:17:40,428 - INFO - Replacement done.
PS C:\Users\25592\AppData\Local\Programs\Termius>`

**Comment by ArcSurge** [comment]
asar是不是没装，使用`npm install -g asar`安装一下

**Comment by ccqiuqiu** [comment]
❯ python lang.py
Traceback (most recent call last):
  File "/Applications/Termius.app/Contents/Resources/lang.py", line 169, in <module>
    main()
  File "/Applications/Termius.app/Contents/Resources/lang.py", line 149, in main
    termius_path = os.path.join(os.getenv('USERPROFILE'), 'AppData', 'Local', 'Programs', 'Termius', 'resources')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType


m1pro电脑运行报错，不知道什么原因
